credentials:
  usernames:
    demouser:
      email: demo@demo.com
      name: Demo User
      password: $2b$12$VVVXcDorioLhh3QYiwZszOInW1mkZPvXLWpsOGIFQkA2qaxGdz5T2
cookie:
  expiry_days: 1
  key: DsdUSuUX5aSlzk/SW9Y8JubnuIQtPoaa+CYQXKaWyoE=
  name: auth_token
